# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorrisJokes' do
  pod 'Alamofire', '~> 5.2'

  target 'ChuckNorrisJokesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckNorrisJokesUITests' do
    # Pods for testing
  end

end
